headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\HFP\\Downloads\\hfpc-git\\hfpc-jonah-game\\site"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
for = "/sw.js"

[headers.values]
Cache-Control = "no-cache"